### ISSUE TITLE
Attempt to invoke virtual method 'android.media.Image$Plane[] android.media.Image.getPlanes()' on a null object reference

### ISSUE THREAD

**Issue by Muzammil-Hussian** [Zetta56/CSAC#1]
**java.lang.NullPointerException**: Attempt to invoke virtual method 'android.media.Image$Plane[] android.media.Image.getPlanes()' on a null object reference
                                         	at com.chromaclicker.app.autoclick.AutoClickService.updateScreenshot(AutoClickService.kt:284)
                                         	at com.chromaclicker.app.autoclick.AutoClickService.captureScreen$lambda-2(AutoClickService.kt:272)
                                         	at com.chromaclicker.app.autoclick.AutoClickService.$r8$lambda$OxaCvBsfXdMKSPwe-Pv6xcrrrAc(Unknown Source:0)
                                         	at com.chromaclicker.app.autoclick.AutoClickService$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:4)
                                         	at android.media.ImageReader$1.run(ImageReader.java:837)
                                         	at android.os.Handler.handleCallback(Handler.java:938)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loopOnce(Looper.java:233)
                                         	at android.os.Looper.loop(Looper.java:344)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8212)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by Zetta56** [comment]
Probably related to this: https://github.com/Zetta56/ChromaClicker/issues/2#issuecomment-2477997152
